---
title: A Simple Kalman Filter
author: admin
date: '2021-01-06'
summary: 'This purposefully simple document explains the main intuition behind Kalman filtering of measurement noise.'
slug: []
categories:
  - macroeconometrics
  - R
tags:
  - pro
math: true
description: Description for the page
bibliography: [bibliography.bib]
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, include = FALSE)
library(plotly)
```


This document is generated with R-Markdown. All related files and code can be found in [GitHub](https://github.com/bbcon/ASimpleKalmanFilterWithR)

# Introduction

This document provides an intuitive and simple introduction to Kalman Filtering. 

The document is organised as follows: the first section motivates the usage of a Kalman Filter in an economic context and reviews the related theory. In particular, it focuses on the key results and ideas behind it--as we shall see, the Kalman Filter's key idea is in reality surprisingly easy to understand. The second section applies the Kalman Filter algorithm to an extremely simple (yet not trivial) state-space model characterised by an AR(1) process as the state equation. The idea behind this is to simplify as much as possible in order to focus on the key elements that will then reveal useful to understand more complex problems. 


This document is mostly based on lecture Notes from Prof. Mark Watson (Princeton University) given as part of the program for Beginning Doctoral students in Economics in Gerzensee taught in March 2020 ((@watson_2020). The lecture notes are themselves heavily based on @hamilton_1994.






# The Kalman Filter for Economics : Motivation, theory, and intuition

## Motivation and simple intuition

We typically observe economic data over time. These data, however, are likely to be noisy. The Kalman Filter (KF) (in an economic context) usually considers two types of potential noise: measurement and structural noise. More precisely, the KF makes the assumption that observed data are subject to measurement errors and are in reality generated by an unobservable process. This unobservable process is known as the state (or transition) equation and is subject to some noise that we can refer to as "structural". In that context, the KF is an algorithm that allows to filter out the measurement noise in order to learn more about the true generating process of the data. In particular, it can be used to learn more about so-called structural shocks which are of crucial importance in DSGE models for instance.

The Kalman Filter was first used in physics but is now widely popular in economics.

## The theory

 **Notation**

The general form of the Kalman filter as presented in Hamilton Chapter 13 (add ref) is given by a "measurement equation":
\begin{align*}
y_t = A'x_t + H'\xi_t + w_t 
\end{align*}
With $E(w_tw_t')=Q$



adfasfadfaf